### ISSUE TITLE
Answer list behavior refinement

### ISSUE THREAD

**Issue by DZ-FSDev** [DevSamLee/FindYourSpeaker#9]
**How to reproduce:**
![FindMySpeakersBR2](https://user-images.githubusercontent.com/85122787/155891988-3e0edc19-97d9-4cb9-8d79-2e634e73bc8c.gif)

**Obstruction**
Bootstrap has high specificity selectors preventing margins from being modified. Below is the conflicting style from `_utilities.scss`
```css
.py-3 {
    padding-top: 1rem!important;
    padding-bottom: 1rem!important;
}
```
